# Generated by Django 6.0.3 on 2026-03-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Kategori Rengi'),
        ),
    ]
