# Generated by Django 6.0.3 on 2026-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0004_alter_review_options_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Enlem'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Boylam'),
        ),
    ]
